name: deep-hedge-rl
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.10
  
  # Scientific Computing
  - numpy=1.24.3
  - pandas=2.2.3
  - matplotlib=3.10.3
  - scipy
  
  # Machine Learning / Deep Learning
  - pytorch=2.7.0
  - cpuonly  # Remove this line if you want GPU support
  
  # Development tools
  - jupyter
  - ipykernel
  - notebook
  
  # Utilities
  - pathlib
  - tqdm
  
  # Install via pip
  - pip
  - pip:
    # Reinforcement Learning
    - stable-baselines3[extra]==2.6.0
    - gymnasium==1.1.1
    
    # Logging and Monitoring
    - tensorboard==2.19.0
    - wandb  # Optional: for experiment tracking
    
    # Data handling
    - cloudpickle==3.1.1
    
    # Graphics and visualization
    - pillow
    - opencv-python
    - pygame
    
    # System monitoring
    - psutil
    
    # Rich formatting (for stable-baselines3)
    - rich
    
    # Mathematical libraries
    - sympy
    
    # File handling
    - fsspec
    
    # Optional: Additional RL libraries
    - ale-py  # Atari Learning Environment
    
    # Development and testing (optional)
    - pytest
    - black  # Code formatter
    - flake8  # Linting